# Generated by Django 5.1.6 on 2025-02-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getmoapp', '0003_staff_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=15)),
                ('doctor', models.CharField(max_length=15)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='ward',
            old_name='ttlbeds',
            new_name='totalbeds',
        ),
    ]
