# Generated by Django 5.1.6 on 2025-02-28 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getmoapp', '0004_appointment_rename_ttlbeds_ward_totalbeds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='fullname',
            new_name='name',
        ),
    ]
