# Generated by Django 5.1.6 on 2025-02-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getmoapp', '0005_rename_fullname_appointment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('department', models.CharField(max_length=15)),
                ('doctor', models.CharField(max_length=15)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='appointment',
        ),
    ]
